EXA_API_KEY="your_exa_api_key_here"
OPENAI_API_KEY="your_openai_api_key_here"
GROQ_API_KEY="your_groq_api_key_here"
AWS_ACCESS_KEY_ID="your_aws_access_key_id_here"
AWS_SECRET_ACCESS_KEY="your_aws_secret_access_key_here"
AWS_REGION_NAME="your_aws_region_name_here"
DYNAMODB_TABLE_NAME="your_dynamodb_table_name_here"
S3_BUCKET_NAME="your_s3_bucket_name_here"